services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=your_postgres_url
      - JWT_SECRET=your_jwt_secret
    depends_on:
      - postgres

  frontend:
    build:
      context: ./pretty-frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:80"  # Or 3001:80 if CRA

  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: servihub
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  postgres-data:
