version: '3.8'
services:
  db:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: test_db
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
