version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3001:3001"
    env_file:
      - ./.env  # Assumes this is at project root
    depends_on:
      - postgres

  frontend:
    build:
      context: ./pretty-frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:80"
    env_file:
      - ./pretty-frontend/.env  # Path to frontend .env

  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: servihub
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  postgres-data:
